### ISSUE TITLE
Crash on startup D:

### ISSUE THREAD

**Issue by quat1024** [elucent/Albedo#1]
Crashlog: https://paste.ee/p/gh98D#s=0&l=175

Minecraft 1.12.1, Forge 14.22.0.2467. AMD Radeon 6800 graphics card. This is the version of Albedo downloaded from Curse. No other mods are loaded.

Hmu if you need any more information <3

**Comment by quat1024** [comment]
I fixed the problem on my end:

In `fastlight.vs` line 96 and `entitylight.vs` line 86, I changed `0f` to `0.0f`. Looks like my graphics driver chokes on parsing a `0f`.

The game at least *runs* - haven't been able to test colored lights just yet because I think there's a Botania-side crash and I don't know of any other Albedo-enabled mods x)

**Comment by elucent** [comment]
Okay, will fix shortly. These bugs are hard to catch, thank you for reporting it!

**Comment by elucent** [comment]
Should be fixed in #2
