### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by saphsara** [elucent/Albedo#13]
MC 1.12.2 server crashing at login and random when in game.  link to crash file https://1drv.ms/t/s!AtL7UzgcOoZ3swAAUhljnHjSe5fd .. if not related to your mod i am sorry .. i was directed to contact you and another mod creator if you can look at report and direct me how to precede further thank you.

**Comment by CreativeMD** [comment]
This issue is related to LittleTiles. I have no idea what is happening, but LittleTiles uses some hacky ways to save performance. For example it hooks into the ChunkRenderDispatcher in order to upload its render data separately.

**Comment by CreativeMD** [comment]
This crash seems to be fixed. (Issue can be closed now)
