### ISSUE TITLE
Glitch in sword sweep effect.

### ISSUE THREAD

**Issue by wouterdebruijn** [elucent/Albedo#17]
I used your mod but saw a glitch with the sword sweep effect. Instead of the normal 3 white stripes, its a big white block. After removing your mode it was fine. I don't know if it is on your end. But just a notice.

Mods I used:
- ActuallyAdditions-1.12.2-r135.jar
- albedo-0.1.3.jar
- appliedenergistics2-rv5-stable-11.jar
- AutoRegLib-1.3-17.jar
- Baubles-1.12-1.5.2.jar
- BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
- BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar
- BloodMagic-1.12.2-2.2.12-97.jar
- Bookshelf-1.12.2-2.3.544.jar
- Botania+r1.10-354.jar
- BrandonsCore-1.12-2.4.2.157-universal.jar
- buildcraft-7.99.17.jar
- Chameleon-1.12-4.1.3.jar
- CodeChickenLib-1.12.2-3.1.9.344-universal.jar
- CoFHCore-1.12.2-4.5.2.19-universal.jar
- CoFHWorld-1.12.2-1.2.0.5-universal.jar
- ComputerCraft1.80pr1.jar
- CTM-MC1.12-0.3.0.15.jar
- DarkUtils-1.12.2-1.8.207.jar
- Decocraft-2.6.0_1.12.2.jar
- Draconic-Evolution-1.12-2.3.11.290-universal.jar
- EnderCore-1.12.2-0.5.31.jar
- EnderIO-1.12.2-5.0.26.jar
- EnderStorage-1.12.2-2.4.3.131-universal.jar
- environmentaltech-1.12.2-2.0.11a.jar
- extrautils2-1.12-1.7.6.jar
- ExtremeReactors-1.12.2-0.4.5.49.jar
- forestry_1.12.2-5.8.0.295.jar
- GalacticraftCore-1.12.2-4.0.1.177.jar
- Galacticraft-Planets-1.12.2-4.0.1.177.jar
- Guide-API-1.12-2.1.5-60.jar
- iChunUtil-1.12.2-7.1.4.jar
- ImmersiveEngineering-0.12-82.jar
- industrialcraft-2-2.8.73-ex112.jar
- intwheel-1.12-1.2.7.jar
- IronBackpacks-1.12.2-3.0.8-12.jar
- ironchest-1.12.2-7.0.40.824.jar
- itemscroller-1.12.0-0.11.0.jar
- jei_1.12.2-4.10.0.198.jar
- journeymap-1.12.2-5.5.2.jar
- LootBags-1.12.2-2.5.6.jar
- lostcities-1.12-2.0.9.jar
- Mantle-1.12-1.3.2.24.jar
- mcjtylib-1.12-3.0.1.jar
- memory_repo
- MicdoodleCore-1.12.2-4.0.1.177.jar
- mods.txt
- Morph-1.12.2-7.1.2.jar
- natura-1.12.2-4.3.2.49.jar
- OpenComputers-MC1.12.2-1.7.2.67.jar
- Pam's+HarvestCraft+1.12.2u.jar
- PTRLib-1.0.2.jar
- Quark-r1.4-124.jar
- RedstoneArsenal-1.12.2-2.5.1.13-universal.jar
- RedstoneFlux-1.12-2.0.2.3-universal.jar
- rftools-1.12-7.53.jar
- rftoolsctrl-1.12-1.9.0.jar
- roots-2-0.104.jar
- spongeforge-1.12.2-2705-7.1.0-BETA-3169.jar
- StorageDrawers-1.12.2-5.3.6.jar
- taiga-1.12.2-1.3.2.jar
- tc6aspects4jei-0.0.1a.jar
- TConstruct-1.12.2-2.10.1.87.jar
- Tesla-1.12.2-1.0.63.jar
- Thaumcraft-1.12.2-6.1.BETA16.jar
- theoneprobe-1.12-1.4.23.jar
- ThermalCultivation-1.12.2-0.3.0.7-universal.jar
- ThermalDynamics-1.12.2-2.5.1.14-universal.jar
- ThermalExpansion-1.12.2-5.5.0.29-universal.jar
- ThermalFoundation-1.12.2-2.5.0.19-universal.jar
- ThermalInnovation-1.12.2-0.3.0.7-universal.jar
- TinkerToolLeveling-1.12.2-1.0.5.jar
- twilightforest-1.12.2-3.7.424-universal.jar
- valkyrielib-1.12.2-2.0.11a.jar
- xnet-1.12-1.7.1.jar
- zerocore-1.12-0.1.2.2.jar
-

**Comment by wouterdebruijn** [comment]
Ow, I was the other post https://github.com/elucent/Albedo/issues/14 its the same issue. Only I dont have DS installed.

**Comment by Davoleo** [comment]
this mod is discontinued and elucent gave up on modding and on open source, you're probably not going to find any fix by him

**Comment by LemADEC** [comment]
EpicSquid took over.

**Comment by Davoleo** [comment]
yep

**Comment by wouterdebruijn** [comment]
Closed this issue because if inactivity, don't know if it is still in affect but I can't be bothered to test that right now.
