### ISSUE TITLE
displaying issues with Optifine and shaders

### ISSUE THREAD

**Issue by 0Navis0** [elucent/Albedo#5]
Albedo causes some displaying issues with lightings when Optifine is present.

**Comment by elucent** [comment]
This is uh, sorta what happens. OptiFfine uses internal shaders that are not compatible with Albedo. Optifine breaks many mods so you can't really expect it to work with stuff like this. So sorry, you'll have to go with one or the other.

**Comment by 0Navis0** [comment]
Ah it's so annoying, Optifine tends to always break other mod. But I suppose there is nothing to do. :(
